### ISSUE TITLE
Add flatMap?

### ISSUE THREAD

**Issue by carlthome** [neverendingqs/pyiterable#71]
Neat package! Could you add a flatMap to make it fully monadic also?

**Comment by neverendingqs** [comment]
Is [mapmany()](http://pyiterable.readthedocs.io/en/v0.4.0/classes/iterable.html#pyiterable.Iterable.mapmany) what you're looking for?

I was probably thinking too much in C# when thinking of a method name (`SelectMany`), but it seems like flatmap might be more appropriate.

Currently considering if I should add another method as an alias.

**Comment by carlthome** [comment]
Ah, sure looks like. :tada: 

No, an alias seems excessive. Again, great package. Have you considered merging with [PyFunctional](http://www.pyfunctional.org/)? It would be nice to consolidate the functional efforts in Python for it to gain more traction. My dream is that Guido eventually would accept a fluent interface for iterables in the standard library.

**Comment by neverendingqs** [comment]
I didn't know about PyFunctional, but it looks like we are trying to do the same thing. Going to join the conversation on https://gitter.im/EntilZha/PyFunctional.
